### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by qingshan-z** [Gepetto/qgv#46] opened 2024-11-20 10:17 UTC
![QQ20241120-181520](https://github.com/user-attachments/assets/0799a5a9-0414-4e34-82f4-3aa2e1081f9a)
May I ask how I can solve this problem？

**Comment by nim65s** [comment] 2024-11-20 10:32
Seems to be a duplicate of #13

**Closed by nim65s** 2024-11-20 10:32 UTC
